export const REFRESH_TOKEN_COOKIE = "refreshToken";
export const ACCESS_TOKEN_COOKIE = "accessToken";
export const REGISTRATION_BONUS = 3000;
export const REGISTRATION_WITH_REFERRAL_EMAIL_BONUS = 1000;
export const PERCENTAGE_FROM_FRIEND_PURCHASE = 10;
export const PERCENTAGE_TO_PAY_BY_BONUS = 30;
